#!/bin/bash

RESULT="result"
AAWK="analyze.awk"
GNUPLOT="./plot.gnuplot"

cat result_* > ${RESULT}

exec > plot

echo "#count win_rate expected_win_rate"
grep 'Score' $RESULT | awk -f $AAWK

exec $GNUPLOT
