#!/bin/bash

#第一个参数是server所在机器ip，第二个参数时同时比赛的场数
#调用实例：./automonitor 160 2

HOST="localhost"
NUM=1

if [ ! -z $1 ]; then
    HOST="192.168.26.$1"
fi

if [ ! -z $2 ]; then
    NUM=$2
fi

for i in `seq 1 $NUM`; do
    PORT=`expr 5000 + $i \* 1000`
    rcssmonitor --server-host $HOST --server-port $PORT --auto-reconnect-mode on --auto-reconnect-wait 5 &
done
